apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: naisflow
  namespace: $namespace
spec:
  desc: Add NAISFlow necessities
  env:
  - name: NO_PROXY
    value: localhost,127.0.0.1,10.254.0.1,.local,.adeo.no,.nav.no,.aetat.no,.devillo.no,.oera.no,.nais.io
  - name: HTTP_PROXY
    value: http://webproxy.nais:8088
  - name: HTTPS_PROXY
    value: http://webproxy.nais:8088
  - name: no_proxy
    value: localhost,127.0.0.1,10.254.0.1,.local,.adeo.no,.nav.no,.aetat.no,.devillo.no,.oera.no,.nais.io
  - name: http_proxy
    value: http://webproxy.nais:8088
  - name: https_proxy
    value: http://webproxy.nais:8088
  imagePullSecrets:
  - name: gpr-credentials
  selector:
    matchLabels:
      naisflow: 'true'
