name: Build and deploy Namespace Decorator

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/namespace-decorator.yaml'
      - 'namespace-decorator/**'

env:
  IMAGE: ghcr.io/navikt/knada-decorators

jobs:
  build-push-notify:
    name: Build Push Notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo TAG="namespace-$(git log -1 --pretty=%ad --date=format:%Y-%m-%d)-$(git log --pretty=format:'%h' -n 1)" >> $GITHUB_ENV
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t $IMAGE:$TAG namespace-decorator
      - run: docker push $IMAGE:$TAG
      - uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          app-id: ${{ secrets.APP_ID }}
      - name: Notify navikt/knada-yaml
        run: |
          curl -X POST https://api.github.com/repos/navikt/knada-yaml/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H 'Authorization: token ${{ steps.get-token.outputs.token }}' \
          --data '{"event_type": "update-image", "client_payload": { "image": "'"${IMAGE}"'", "tag": "'"${TAG}"'" }}'
