name: Build and deploy Profile Watcher

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/profile-watcher.yaml'
      - 'profile-watcher/**'

env:
  KUBEFLOW_REPO_URL: https://api.github.com/repos/navikt/kubeflow-yaml/dispatches

jobs:
  build-naisflow-dataverk:
    name: Build profile watcher image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set image tag
        run: |
          echo ::set-env name=IMAGE_TAG:profile-watcher:$(git log -1 --pretty=%ad --date=format:%Y-%m-%d)-$(git log --pretty=format:'%h' -n 1)
      - name: Login to Github Package Registry
        env:
          DOCKER_USERNAME: x-access-token
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin docker.pkg.github.com
      - name: Build dataverk image
        run: |
          cd profile-watcher
          docker build -t "docker.pkg.github.com"/"$GITHUB_REPOSITORY"/"$NAME":"$IMAGE_TAG" .
      - name: Push dataverk image
        run: docker push "docker.pkg.github.com"/"$GITHUB_REPOSITORY"/"$NAME":"$IMAGE_TAG"
      - name: Notify navikt/kubeflow-yaml
        run: |
          curl -X POST "${KUBEFLOW_REPO_URL}" \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.KUBEFLOW_YAML_ACCESS_TOKEN }} \
          --data '{"event_type": "profile-watcher-tag, "client_payload": { "tag": "'"${IMAGE_TAG}"'" }}'
